### ISSUE TITLE
How to obtain norm.pkl, pca.pkl and annot_dict?

### ISSUE THREAD

**Issue by jane-pyc** [y-hwang/gLM#1]
Hello, thanks for this great work!

I wonder how to get the norm.pkl and annot_dict of all training data?

**data/batch_data.py**
`norm_factors_f = "norm.pkl"`
`pca_pkl_f = "pca.pkl"`

**operon_logreg.py**
`annot_dict= read_annot_file(annot_path)`

Could you release the complete data preprocessing code?

Thanks for the help!

**Comment by y-hwang** [comment]
norm.pkl and pca.pkl are found in gLM/data. annot_dict is found as gLM/data/ecoli_annot_data/operon.annot
